apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper-workflow
spec:
  selector:
    matchLabels:
      app: skipper-workflow
  template:
    metadata:
      labels:
        app: skipper-workflow
    spec:
      containers:
        - image: katanaml/skipper-workflow:latest
          name: skipper-workflow
          imagePullPolicy: IfNotPresent
          env:
            - name: LOGGER_URL
              value: "http://skipper-logger:5001/api/v1/skipper/logger/log_workflow"
          livenessProbe:
            httpGet:
              path: /api/v1/skipper/workflow/
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 600
            failureThreshold: 3
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: skipper-workflow
spec:
  selector:
    app: skipper-workflow
  ports:
    - port: 5000