version: '3.9'

services:
  rabbitmq:
    image: katanaml/rabbitmq-service
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./backend-rabbitmq/etc/:/etc/backend/
      - ./backend-rabbitmq/data/:/var/lib/backend/
      - ./backend-rabbitmq/logs/:/var/log/backend/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=welcome1
      - RABBITMQ_NODENAME=rabbitnode@localhost
      - RABBITMQ_USER=skipper
      - RABBITMQ_PASSWORD=welcome1
    networks:
      - network1
    restart: always

  logger:
    image: katanaml/skipper-logger
    build:
      context: ./logger
      dockerfile: Dockerfile
    container_name: skipper-logger
    ports:
      - 5001:5001
    command: uvicorn endpoint:app --port=5001 --host 0.0.0.0
    networks:
      - network1

  workflow:
    image: katanaml/skipper-workflow
    build:
      context: ./workflow
      dockerfile: Dockerfile
    container_name: skipper-workflow
    ports:
      - 5000:5000
    command: uvicorn endpoint:app --port=5000 --host 0.0.0.0
    environment:
      - LOGGER_URL=http://logger:5001/api/v1/skipper/logger/log_workflow
    networks:
      - network1

  api:
    image: katanaml/skipper-api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: skipper-api
    ports:
      - 8000:8000
    command: uvicorn endpoint:app --port=8000 --host 0.0.0.0
    environment:
      - WORKFLOW_URL=http://workflow:5000/api/v1/skipper/workflow/
      - LOGGER_PRODUCER_URL=http://logger:5001/api/v1/skipper/logger/log_producer
      - RABBITMQ_BROKER=pyamqp://skipper:welcome1@rabbitmq//
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=skipper
      - RABBITMQ_PASSWORD=welcome1
    networks:
      - network1
    depends_on:
      - rabbitmq

  api-celery:
    image: katanaml/skipper-api-celery
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: skipper-api-celery
    command: celery -A api.worker worker --loglevel=INFO
    environment:
      - WORKFLOW_URL=http://workflow:5000/api/v1/skipper/workflow/
      - LOGGER_PRODUCER_URL=http://logger:5001/api/v1/skipper/logger/log_producer
      - RABBITMQ_BROKER=pyamqp://skipper:welcome1@rabbitmq//
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=skipper
      - RABBITMQ_PASSWORD=welcome1
    networks:
      - network1
    depends_on:
      - api

  data-service:
    image: katanaml/data-service
    build:
      context: ./services/dataservice
      dockerfile: Dockerfile
    container_name: data-service
    command: python main.py
    environment:
      - LOGGER_RECEIVER_URL=http://logger:5001/api/v1/skipper/logger/log_receiver
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=skipper
      - RABBITMQ_PASSWORD=welcome1
      - QUEUE_NAME=skipper_data
      - SERVICE_NAME=data
    networks:
      - network1
    depends_on:
      - rabbitmq

networks:
  network1:
    name: katana-network
