version: '3.9'

services:
  rabbitmq:
    image: katanaml/rabbitmq-service
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672

  logger:
    image: katanaml/skipper-logger
    build:
      context: ./logger
      dockerfile: Dockerfile
    container_name: skipper-logger
    ports:
      - 5001:5001

  workflow:
    image: katanaml/skipper-workflow
    build:
      context: ./workflow
      dockerfile: Dockerfile
    container_name: skipper-workflow
    ports:
      - 5000:5000

  api:
    image: katanaml/skipper-api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: skipper-api
    command: uvicorn endpoint:app --port=8000 --host 0.0.0.0
    ports:
      - 8000:8000

  # Sample set of services, you should replace with your own services
  data-service:
    image: katanaml/data-service
    build:
      context: ./services/dataservice
      dockerfile: Dockerfile
    container_name: data-service

  training-service:
    image: katanaml/training-service
    build:
      context: ./services/trainingservice
      dockerfile: Dockerfile
    container_name: training-service

  serving-service:
    image: katanaml/serving-service
    build:
      context: ./services/servingservice
      dockerfile: Dockerfile
    container_name: serving-service
  # Sample set of services, you should replace with your own services
