apiVersion: v1
kind: Secret
metadata:
  name: api-celery-secret
type: Opaque
data:
  RABBITMQ_USER: c2tpcHBlcg==
  RABBITMQ_PASSWORD: d2VsY29tZTE=
  RABBITMQ_BROKER: cHlhbXFwOi8vc2tpcHBlcjp3ZWxjb21lMUByYWJiaXRtcS0wLnJhYmJpdG1xLnJhYmJpdHMuc3ZjLmNsdXN0ZXIubG9jYWwvLw==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper-api-celery
spec:
  selector:
    matchLabels:
      app: skipper-api-celery
  template:
    metadata:
      labels:
        app: skipper-api-celery
    spec:
      containers:
        - image: katanaml/skipper-api:latest
          name: skipper-api-celery
          command: ["celery"]
          args: ["-A", "api.worker", "worker", "--loglevel=INFO"]
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKFLOW_URL
              value: "http://skipper-workflow:5000/api/v1/skipper/workflow/"
            - name: LOGGER_PRODUCER_URL
              value: "http://skipper-logger:5001/api/v1/skipper/logger/log_producer"
            - name: RABBITMQ_BROKER
              valueFrom:
                secretKeyRef:
                  name: api-celery-secret
                  key: RABBITMQ_BROKER
            - name: RABBITMQ_HOST
              value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: api-celery-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-celery-secret
                  key: RABBITMQ_PASSWORD